config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'sitters#index'
    get '/index' => 'sitters#index', as: 'main'
    get '/sitters/:id' => 'sitters#show', as: 'sitter'
    get '/profile' => 'sitters#profile', as: 'profile'
    get '/profile/new' => 'sitters#new', as: 'new_profile'
    post '/profile' => 'sitters#create'
    post '/index' => 'sitters#search', as: 'search'

    get '/profile/edit' => 'sitters#edit', as: 'edit_profile'
    patch '/sitters/:id' => 'sitters#update'
    get '/profile/edit/timeslots/:id' => 'timeslots#edit', as: 'edit_timeslot'
    patch '/profile/edit/timeslots/:id' => 'timeslots#update'

    get '/sitters/:id/bookings/new' => 'bookings#new', as: 'new_booking' #testing
    get '/users/bookings' => 'bookings#show', as: 'bookings'
    post '/sitters/:id/bookings' => 'bookings#create', as: 'create_booking'
    patch '/users/bookings' => 'bookings#update', as: 'update_booking'

    get '/timeslots/new' => 'timeslots#new', as: 'new_timeslot'
    post '/timeslots' => 'timeslots#create'
end

app/models/booking.rb
require 'date'

class Booking < ApplicationRecord

    belongs_to :sitter

    belongs_to :user

    validate :time_logic, on: :create




    def time_logic
        if self.start_date.past?
            errors.add(:available_dates, "We can't timetravel yet. Please use a more current date")
        elsif self.start_date > self.end_date
            errors.add(:available_dates, "End date must be later than Start Date")
        end
    end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
    def new
        @sitter = Sitter.find(params[:id])
        @timeslots = Timeslot.where(sitter: @sitter)

        @earliest =  Timeslot.where(sitter: @sitter).minimum('available_start_date')
        @latest =Timeslot.where(sitter: @sitter).maximum('available_end_date')
    end

    def create
        @booking = Booking.new(booking_params)
        @sitter = Sitter.find(params[:id])
        @timeslots = Timeslot.where(sitter: @sitter)
        @timeslots.each do |timeslot|
            if (@booking.start_date >= timeslot.available_start_date && @booking.end_date <= timeslot.available_end_date)
                @timeslot = timeslot
                @booking.sitter = @sitter
                @booking.user = current_user
                days = @booking.end_date - @booking.start_date
                @booking.price = @booking.sitter.price.to_i * (days.to_i + 1)
                @booking.save
                redirect_to(bookings_path) and return
            end
        end
        redirect_back(fallback_location: root_path)
    end

    def show
        @mybookings = Booking.where(user: current_user)
        @bookings = Booking.where(sitter: current_user.sitter)
    end

    def update

        @book = Booking.new(booking_params);
        @booking = Booking.find(@book.id);
        if @book.status == true
            timeslots = Timeslot.where(sitter: current_user.sitter)
            timeslots.each do |timeslot|
                if @booking.start_date >= timeslot.available_start_date && @booking.end_date <= timeslot.available_end_date
                    @timeslot = timeslot
                end
            end
            if @timeslot == nil
                redirect_to bookings_path and return
            end
            @bookings = Booking.where(sitter: current_user.sitter).where.not('start_date > ? AND end_date > ?', @booking.end_date, @booking.end_date).where.not('start_date < ? AND end_date < ?', @booking.start_date, @booking.start_date)
            @bookings.each do |booking|
                booking.update(status: false)
            end
            if @booking.start_date == @timeslot.available_start_date && @booking.end_date < @timeslot.available_end_date
                @timeslot.update(available_start_date: @booking.end_date + 1)
                @booking.update(status: true)
            elsif @booking.end_date == @timeslot.available_end_date && @booking.start_date > @timeslot.available_start_date
                @timeslot.update(available_end_date: @booking.start_date - 1)
                @booking.update(status: true)
            elsif @booking.start_date > @timeslot.available_start_date && @booking.end_date < @timeslot.available_end_date
                new_timeslot = Timeslot.new(available_start_date: @timeslot.available_start_date, available_end_date: @booking.start_date - 1, sitter: @timeslot.sitter)
                new_timeslot.save
                @timeslot.update(available_start_date: @booking.end_date + 1)
                @booking.update(status: true)
            elsif @booking.start_date == @timeslot.available_start_date && @booking.end_date == @timeslot.available_end_date
                @timeslot.destroy
                @booking.update(status: true)
            else
                render plain: "SOMETHING IS WRONG IN BOOKING UPDATE"
            end
        else
            @booking.update(status: false)
        end
        redirect_to bookings_path
    end

private

    def booking_params
        params.require(:booking).permit(:start_date, :end_date, :status, :id)
    end

end

app/views/bookings/new.html.erb
<div class="container h-100 mt-3" id="book">
<h1>Bookings</h1>
<h3>Available Timeslots</h3>
<% @timeslots.each_with_index do |timeslot, i| %>
<div>
    <label><strong>Timeslot <%=i+1%>:</strong></label>
        <%= timeslot.available_start_date.strftime("%d %b %Y") %>
        <%if timeslot.available_start_date != timeslot.available_end_date %>
         to
        <%= timeslot.available_end_date.strftime("%d %b %Y") %>
        <%end%>
      </div>
<% end %>

<%= form_with scope: :booking, url: create_booking_path, local: true do |form| %>

 		<div class="form-row ">
  			<div class="form-group col-md-6 ">
  				<%= form.label :Start %><br>
  				<%= form.text_field :start_date , :type=>"date", :class=>"form-control", :min=>@earliest, :max=> @latest, :required => true %>
  			</div>
  			<div class="form-group col-md-6">
  				<%= form.label :End %><br>
  				<%= form.text_field :end_date , :type=>"date", :class=>"form-control", :min=> @earliest, :max=> @latest, :required => true %>
  			</div>
  		</div>
 		<div class="actions">
  			<%= form.submit class: "btn btn-outline-success" %>
  		</div>
<% end %>
</div>

app/views/bookings/show.html.erb
<div class="container h-100 mt-3" id="show_booking">


    <h1>Bookings sent</h1>
    <% if @mybookings.length == 0 %>
        <div class=row>
            <div class="col">No Current Bookings</div>
        </div>
    <% else %>
        <div class=row>
            <div class="col"><strong>Sitter</strong></div>
            <div class="col"><strong>Start</strong></div>
            <div class="col"><strong>End</strong></div>
            <div class="col"><strong>Cost</strong></div>
            <div class="col"><strong>Status</strong></div>
        </div>
        <% @mybookings.each do |mybooking| %>
            <div class=row>
                <div class="col">
                    <%= mybooking.sitter.user.username %>
                </div>
                <div class="col">
                    <%= mybooking.start_date.strftime("%d %b %Y") %>
                </div>
                <div class="col">
                    <%= mybooking.end_date.strftime("%d %b %Y") %>
                </div>
                <div class="col">
                    $<%= mybooking.price %>
                </div>
                <div class="col">
                    <% if mybooking.status == true %>
                    Accepted
                        <% if !mybooking.sitter.phone.empty? %>
                    <a href="https://api.whatsapp.com/send?phone=+65<%= mybooking.sitter.phone %>" target="_blank" rel="noopener noreferrer"><i class="fab fa-whatsapp fa-2x"></i></a>
                        <% else %>
                        <a href="https://mail.google.com/mail/?view=cm&fs=1&to=<%= mybooking.sitter.user.email %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-at fa-2x"></i></a>
                        <% end %>
                    <% elsif mybooking.status == false %>
                    Declined
                    <% else %>
                    Pending
                    <% end %>
                </div>
            </div>
        <% end %>
    <% end %>


    <% if current_user.sitter %>
        <h1>Bookings received</h1>
            <% if @bookings.length > 0 %>
                <div class=row>
                    <div class="col-2"><strong>User</strong></div>
                    <div class="col-2"><strong>Start Date</strong></div>
                    <div class="col-2"><strong>End Date</strong></div>
                    <div class="col-1"><strong>Price</strong></div>
                    <div class="col-2"><strong>Status</strong></div>
                    <div class="col"><strong>Action</strong></div>
                </div>
                <% @bookings.each do |booking| %>
                    <div class=row>
                        <div class="col-2">
                            <%= booking.user.username %>
                        </div>
                        <div class="col-2">
                            <%= booking.start_date.strftime("%d %b %Y") %>
                        </div>
                        <div class="col-2">
                            <%= booking.end_date.strftime("%d %b %Y") %>
                        </div>
                        <div class="col-1">
                            <% days =  booking.end_date - booking.start_date %>
                            $<%= booking.sitter.price.to_i * (days.to_i + 1) %>
                        </div>
                        <div class="col-2">
                            <% if booking.status == true %>
                            Accepted
                                <% if booking.user.sitter %>
                                    <% if !booking.user.sitter.phone.empty? %>
                                        <a href="https://api.whatsapp.com/send?phone=+65<%= booking.user.sitter.phone %>" target="_blank" rel="noopener noreferrer"><i class="fab fa-whatsapp fa-2x"></i></a>
                                    <% else %>
                                        <a href="https://mail.google.com/mail/?view=cm&fs=1&to=<%= booking.user.email %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-at fa-2x"></i></a>
                                    <% end %>
                                <% else %>
                                <a href="https://mail.google.com/mail/?view=cm&fs=1&to=<%= booking.user.email %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-at fa-2x"></i></a>
                                <% end %>
                            <% elsif booking.status == false %>
                            Declined
                            <% else %>
                            Pending
                            <% end %>
                        </div>
                        <div class="col">
                            <% if booking.status == nil %>
                                <div class="row">
                                    <%= form_with scope: :booking, model: @booking, method: "patch", local: true do |form| %>
                                        <%= form.hidden_field :status, :value => true %>
                                        <%= form.hidden_field :id, :value => booking.id %>
                                        <%= form.submit 'Accept', :class=>"btn btn-outline-success", :style=>"margin:0 10px 0 0"%>
                                    <% end %>
                                    <%= form_with scope: :booking, model: @booking, method: "patch", local: true do |form| %>
                                        <%= form.hidden_field :status, :value => false %>
                                        <%= form.hidden_field :id, :value => booking.id %>
                                        <%= form.submit 'Decline', :class=>"btn btn-outline-danger"%>
                                    <% end %>
                                </div>
                            <% else %>
                                <div class="row">
                                    Completed
                                </div>
                            <% end %>
                        </div>
                    </div>
            <% end %>
        <% else %>
            <p>No Pending Sitter Bookings</p>
        <% end %>
    <% end %>
</div>