config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'sitters#index'
    get '/index' => 'sitters#index', as: 'main'
    get '/sitters/:id' => 'sitters#show', as: 'sitter'
    get '/profile' => 'sitters#profile', as: 'profile'
    get '/profile/new' => 'sitters#new', as: 'new_profile'
    post '/profile' => 'sitters#create'
    post '/index' => 'sitters#search', as: 'search'

    get '/profile/edit' => 'sitters#edit', as: 'edit_profile'
    patch '/sitters/:id' => 'sitters#update'
    get '/profile/edit/timeslots/:id' => 'timeslots#edit', as: 'edit_timeslot'
    patch '/profile/edit/timeslots/:id' => 'timeslots#update'

    get '/sitters/:id/bookings/new' => 'bookings#new', as: 'new_booking' #testing
    get '/users/bookings' => 'bookings#show', as: 'bookings'
    post '/sitters/:id/bookings' => 'bookings#create', as: 'create_booking'
    patch '/users/bookings' => 'bookings#update', as: 'update_booking'

    get '/timeslots/new' => 'timeslots#new', as: 'new_timeslot'
    post '/timeslots' => 'timeslots#create'
end

app/models/sitter.rb
class Sitter < ApplicationRecord
    belongs_to :user

    has_many :timeslots

    has_many :bookings

    has_and_belongs_to_many :pets
    validate :phone_logic, on: [:create, :update]
    def phone_logic
      if self.phone =~ /^(?:\d{8,})|(?=\d{4}+ \d{4})/
        if !Sitter.where(self.id.to_s)
          if Sitter.where(phone: phone).exists?
            errors.add(:phone_no, "Phone number taken")
          end
        end
      else
        errors.add(:phone_no, "Invalid input.")
      end
    end
end

app/controllers/sitters_controller.rb
class SittersController < ApplicationController
  before_action :authenticate_user!

      def index
          @sitters = Sitter.where(:is_visible => true).where.not(:user => current_user)
          @pets = Pet.all
      end

      def search
        @sitters_group_1 = Sitter.where(:is_visible => true).where.not(:user => current_user)
        @sitters_group_2 = Sitter.where(:is_visible => true).where.not(:user => current_user)
        #find sitters group 1 if neither dates are empty
        if (search_params[:available_start_date] != "" &&search_params[:available_end_date]) && (search_params[:available_start_date] != "") && (search_params[:available_end_date] != "")
            @timeslot = Timeslot.where("available_start_date <= ? and available_end_date >= ?",search_params[:available_start_date],search_params[:available_end_date])
            @sitters_group_1 = @timeslot.map { |timeslot|
                timeslot.sitter
              }
        end
        #find sitters group 2 if pet not empty
        if search_params[:pet_id] != ""
          @pet = Pet.find(search_params[:pet_id])
          @sitters_group_2 = @pet.sitters
        end
          @sitters_group_3 = (@sitters_group_1 & @sitters_group_2).uniq
          @sitters = @sitters_group_3.select do |sitter|
              sitter.is_visible == true && sitter.user != current_user
        end

          @pets = Pet.all
          render "index"
      end

      def profile
        @sitter = Sitter.find_by(user: current_user)
        if @sitter
        else
          redirect_to new_profile_path
        end
      end

      def new
        @pets = Pet.all
      end

      def show
        @sitter = Sitter.find(params[:id])
      end

      def create
        @sitter = Sitter.new(sitter_params)
        @timeslot = Timeslot.new(timeslot_params)
        @sitter.user = current_user
        if sitter_params[:picture]
            file = sitter_params[:picture].path
            cloudinary_file = Cloudinary::Uploader.upload(file)
            if cloudinary_file
              @sitter.picture = cloudinary_file['url']
            end
        else
          @sitter.picture ='https://res.cloudinary.com/do3q60bdd/image/upload/v1580874417/Profile_pics/b40892de6be2c24a2a8efa6d84fd1fd6_pwktxl.png'
        end

        if(@sitter.pet_ids.length == 0)
          @sitter.pets << Pet.all
        end
        # empty checkboxes are not sent, therefore nil
        if !@sitter.is_visible
          @sitter.is_visible = false
        end

        if @sitter.save
            @timeslot.sitter = current_user.sitter
            if @timeslot.available_start_date == nil || @timeslot.available_end_date == nil
                redirect_to new_timeslot_path
            else
                if @timeslot.save
                    redirect_to profile_path
                else
                    redirect_to new_timeslot_path
                end
            end
        else
          @pets = Pet.all
          render 'new'
        end
      end

      def edit
        @sitter = Sitter.find_by(user: current_user)
        if @sitter
          @pets = Pet.all
          @timeslots = Timeslot.where(sitter: current_user.sitter)
        else
          redirect_to new_profile_path
        end
      end

      def update
        @sitter = Sitter.find_by(user: current_user)
        if !sitter_params[:is_visible]
          @sitter.is_visible = false
        end
        update_pic = true
        if !sitter_params[:picture]
          sitter_params[:picture] = @sitter.picture
          update_pic = false
        end
        if @sitter.update(sitter_params)
            if(@sitter.pet_ids.length == 0)
                @sitter.pets << Pet.all
                @sitter.save
            end
            if update_pic
              file = sitter_params[:picture].path
              cloudinary_file = Cloudinary::Uploader.upload(file)
              @sitter.picture = cloudinary_file['url']
              @sitter.save
            end
          redirect_to profile_path
        else
        @sitter = Sitter.find_by(user: current_user)
            @pets = Pet.all
            @timeslots = Timeslot.where(sitter: current_user.sitter)
            render 'edit'
        end
      end

      def destroy
        @sitter = Sitter.find(params[:id])
      end

      private

      def sitter_params
        params.require(:sitter).permit(:phone, :description, :location, :price, :about, :picture, :is_visible, :pet_ids=>[])
      end

      def timeslot_params
        params.require(:sitter).permit(:available_start_date, :available_end_date)
      end

      def search_params
        params.require(:sitter).permit(:available_start_date, :available_end_date, :pet_id)
      end
end

app/views/sitters/edit.html.erb
<section id='edit-profile'>
  <div style="width:70%;" class="mx-auto pb-5 pt-3">
<h1>Edit profile</h1>

<%= form_with scope: :sitter, model: @sitter, local: true do |form| %>

  <div class="form-row ">
			<div class="form-group col-md-6 ">
    <%= form.label :phone %><br>
    <%= form.text_field :phone, autofocus: true, :class=>"form-control", :required => true%>
			</div>
      <div class="form-group col-md-6">
				<%= form.label :price_per_day_in%> $<br>
				<%= form.text_field :price, :class=>"form-control" , :required => true, :type=>"number", :min=>"0"%>

			</div>
	</div>
  		<div class="form-group">
			<%= form.label :location %><br>
			<%= form.text_field :location , :class=>"form-control", :required => true, id:"autocomplete", placeholder: "Enter your address" %>
		</div>
		<div class="form-group">
			<%= form.label :about %><br>
			<%= form.text_area :description, :class=>"form-control", :rows => 3, :style=>"resize:none;", :maxlength=>"1000" %>
		</div>
			<%= form.label :avatar_url %><br>
		<div class="input-group">
		  <div class="input-group-prepend">
		    <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
		  </div>
		  <div class="custom-file">
		    <%= form.file_field :picture, :type=>"file", :class=>"custom-file-input", :accept=>'image/png, image/jpeg, image/jpg', 'aria-describedby'=>"inputGroupFileAddon01"%>
		    <label class="custom-file-label" for="picture">Choose file</label>
		  </div>
		</div>
		<div class="form-row mt-3">
			<div class="field form-group col-md-2">
				<%= form.check_box :is_visible, { :multiple => false }, true, false %>
				<%= form.label :public %>
			</div>
      <div class="field form-group col-md-6">
				<%=label_tag "Pet preferences:"%>
				<%= form.collection_check_boxes(:pet_ids, @pets, :id, :animal) do |a| %>
				<%= a.label class:"label-checkbox" do%>
				<%=a.check_box + " " + a.text%>s
				<%end%>
				<% end %>
			</div>
		</div>
    		<div class="actions">
			<%= form.submit class: "btn btn-outline-success" %>
		</div>
<% end %>

<hr style="border: 1px solid black" class="mt-4"/>

<h1>Edit Timeslots</h1>

<% if !@sitter.timeslots.empty? %>

          <% @sitter.timeslots.each do |t| %>
            <%= link_to edit_timeslot_path(t.id) do %>
            <span class="mr-5"><%= t.available_start_date.strftime("%d %b %Y")%> to <%= t.available_end_date.strftime("%d %b %Y")%></span>
            <% end %>
          <% end %>

        <%else %>
        <p>No available timeslot</p>
		<%= link_to 'Add Timeslot', new_timeslot_path %>
        <% end %>

</div>
</section>

<script>

function placesSearch(){

	var options = {
   		componentRestrictions: {country: "sg"} // 2-letters code
	};
	const input = document.querySelector("#autocomplete")
	let autocomplete = new google.maps.places.Autocomplete(input, options)
}

$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});

</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLmBOaPbZ6QachL4NResvEtu8ChjOQGfw&libraries=places&callback=placesSearch"></script>
>>>>>>> master

app/views/sitters/index.html.erb
<section id="index">
	<div class='container'>
		<h1 class="text-center pt-3">Pet Sitters</h1>
		<%= form_with scope: :sitter, url: search_path, local: true do |form| %>

		<div class="form-inline d-flex justify-content-center pt-4">
			<div class="form-group">
				<%= form.label :Start_date, class: "pl-3 pl-sm-0" %>:
				<%= form.text_field :available_start_date , :type=>"date", :class=>"form-control ml-3 mr-3", :min=> Date.today%>
			</div>


			<div class="form-group pt-0 pt-sm-2 pt-md-0 pl-1">
				<%= form.label :End_date, class: "pl-3 pl-sm-0" %>:
				<%= form.text_field :available_end_date , :type=>"date", :class=>"form-control ml-3 mr-3", :min=> Date.today%>
			</div>
		</div>
		<div class="form-inline d-flex justify-content-center pt-1 pt-sm-3 pt-md-4">
			<div class="form-group col-xs-4">
				<%= form.label :pet, class: "pl-3 pl-sm-0" %>:
				<%= form.collection_select :pet_id, @pets, :id, :animal, {label: 'Pets:', :include_blank => ("Select..."), hide_label: true}, {:class=> "form-control ml-3 mr-3"} %>
			</div>
			<div class="col-xs-4">
				<div class="actions pl-2">
					<%= form.submit "Search", :class=> "btn btn-outline-success mt-3 mt-sm-0 ml-4 ml-sm-0" %>
				</div>
			</div>
		</div>
	</div>
	<% end %>

	<div class="row mt-2 d-flex justify-content-center mx-auto">
		<% @sitters.each do |sitter| %>
		<div class="col-8 col-lg-5 mt-4">
			<div class="card profile-card-5">
				<a href='/sitters/<%= sitter.id %>' class='btn btn-success profile-link'>See more</a>
				<div class="card-img-block">
					<%= image_tag sitter.picture, src: 'Image not found', onerror: 'this.error=null;this.src="https://pngimage.net/wp-content/uploads/2018/05/default-user-profile-image-png-7.png"', class:"card-img-top" %>
				</div>
				<div class="card-body pt-0">
					<h5 class="card-title"><%= sitter.user.username %>
						<span class="float-right animals">
							<% sitter.pets.each do |pet| %>
							<% if pet.animal == "dog" %>
							<i class="fas fa-dog" style='font-size: 25px;'></i><br />
							<% elsif pet.animal == "cat" %>
							<i class="fas fa-cat" style='font-size: 25px;'></i><br />
							<% elsif pet.animal == "bird" %>
							<i class="fas fa-dove" style='font-size: 25px;'></i><br />
							<% end %>
							<% end %>
						</span>
					</h5>
					<% if !sitter.timeslots.empty? %>
					<span>Available: <%= sitter.timeslots[0].available_start_date.strftime("%d %b %Y") %>...
						<% end %>
						<span class="float-right card-text text-right">$<%= sitter.price %>/day</span>
				</div>
			</div>
		</div>
		<% end  %>
	</div>
	</div>
</section>

app/views/sitters/new.html.erb
<section id="new-profile">
	<div style="width:70%;" class=" mx-auto pt-5 pb-3">
		<h1>Create pet sitter profile</h1>

		<%= form_with scope: :sitter, url: profile_path, local: true do |form| %>
		<div class="form-row ">
			<div class="form-group col-md-6 ">
				<%= form.label :phone %><br>
				<%= form.text_field :phone, autofocus: true, :class=>"form-control", :required => true%>
					<span style="color:red;font-size: 12px"><%= show_errors(@sitter, :phone_no)%></span>
			</div>
			<div class="form-group col-md-6">
				<%= form.label :price_per_day_in%> $<br>
				<%= form.file_field  :price, :class=>"form-control", :required => true, :type=>"number", :min=>"0" %>
			</div>
		</div>
		<div class="form-row ">
			<div class="form-group col-md-6 ">
				<%= form.label :available_start_date %><br>
				<%= form.text_field :available_start_date , :type=>"date", :class=>"form-control", :min=>Date.today %>
			</div>
			<div class="form-group col-md-6">
				<%= form.label :available_end_date %><br>
				<%= form.text_field :available_end_date , :type=>"date", :class=>"form-control", :min=>Date.today%>
				 <span style="color:red;font-size: 12px"><%= show_errors(@timeslot, :available_dates)%></span>
			</div>
		</div>
		<div class="form-group">
			<%= form.label :location %><br>
			<%= form.text_field :location , :class=>"form-control", :required => true, id:"autocomplete", placeholder: "Enter your address"%>
		</div>
		<div class="form-group">
			<%= form.label :about %><br>
			<%= form.text_area :description, :class=>"form-control", :rows => 3, :style=>"resize:none;", :maxlength=>"1000" %>
		</div>
			<%= form.label :avatar_url %><br>
		<div class="input-group">
		  <div class="input-group-prepend">
		    <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
		  </div>
		  <div class="custom-file">
		    <%= form.file_field :picture, :type=>"file", :class=>"custom-file-input", :accept=>'image/png, image/jpeg, image/jpg', 'aria-describedby'=>"inputGroupFileAddon01"%>
		    <label class="custom-file-label" for="picture">Choose file</label>
		  </div>
		</div>
		<div class="form-row mt-3">
			<div class="field form-group col-md-2">
				<%= form.check_box :is_visible, { :multiple => false }, true, false %>
				<%= form.label :public %>
			</div>
			<div class="field form-group col-md-6">
				<%=label_tag "Pet preferences:"%>
				<%= form.collection_check_boxes(:pet_ids, @pets, :id, :animal) do |a| %>
				<%= a.label class:"label-checkbox" do%>
				<%=a.check_box + " " + a.text%>s
				<%end%>
				<% end %>
			</div>
		</div>
		<div class="actions">
			<%= form.submit class: "btn btn-outline-success" %>
		</div>
		<% end %>
	</div>
</section>
<script>

function placesSearch(){

	var options = {
   		componentRestrictions: {country: "sg"} // 2-letters code
	};
	const input = document.querySelector("#autocomplete")
	let autocomplete = new google.maps.places.Autocomplete(input, options)
}
$(".custom-file-input").on("change", function() {
  var fileName = $(this).val().split("\\").pop();
  $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
});
</script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLmBOaPbZ6QachL4NResvEtu8ChjOQGfw&libraries=places&callback=placesSearch"></script>

app/views/sitters/profile.html.erb
<section id="profile">
  <% if flash[:error] %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-danger mt-2 mt-sm-0">
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <div class="container h-100">
    <div class="row justify-content-center align-self-center pt-3">

      <div class="col-8 col-md mx-auto d-flex flex-column">
        <h1 class="align-self-center"><%= @sitter.user.username%> <span
          style="font-size:20px"><%= link_to 'Edit', edit_profile_path %></span></h1>
                <%= image_tag @sitter.picture, style: "width:75%; border-radius: 50px", src: 'Image not found', onerror: 'this.error=null;this.src="https://pngimage.net/wp-content/uploads/2018/05/default-user-profile-image-png-7.png"', class:"img-responsive align-self-center mb-3" %>
        <h4 class="text-center">

        <% @sitter.pets.each do |pet| %>
          <span>● <%= pet.animal %>s </span>
        <% end %>
        <h4 class="text-center"><span class="h5 text-muted"> $<%= @sitter.price%> per day</span></h4>
        <h4 class="text-center"><span class="h5 text-italic"><i class="fas fa-phone"></i> <%= @sitter.phone %></span>
        </h4>
      </div>

      <div class="col-8 col-md mx-auto d-flex flex-column align-items-center pt-5">
        <h4>Available Dates</h4>
        <% if !@sitter.timeslots.empty? %>
      <% @sitter.timeslots.each do |t| %>
      <%= link_to edit_timeslot_path(t.id) do %>
      <p><%= t.available_start_date.strftime("%d %b %Y")%> to <%= t.available_end_date.strftime("%d %b %Y")%></p>
      <% end %>
      <% end %>
      <%else %>
      <p>No available timeslot</p>
      <%= link_to 'Add Timeslot', new_timeslot_path %>
      <% end %>
    </div>

    <div class="col-8 col-md mx-1 my-1">
      <div class="container-fluid h-100 pt-5">
        <% if @sitter.location %>
        <iframe width="100%" height="100%" frameborder="0" style="border:0" class="img-responsive"
          src="https://www.google.com/maps/embed/v1/search?q=<%= @sitter.location.gsub(/\s+/, '+') %>,+Singapore&key=AIzaSyBLmBOaPbZ6QachL4NResvEtu8ChjOQGfw"
          allowfullscreen></iframe>
          <% else %>
            <%=image_tag "https://joomly.net/frontend/web/images/googlemap/map.png", :class =>'img-responsive', :style=>"width:100%;"%>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row d-flex flex-row justify-content-center align-self-center mt-5">
      <div class="container w-75">
        <h4 class='text-center'>About me</h4>
        <p style="white-space: pre-wrap; overflow-wrap: break-word;" class="text-center"><%= @sitter.description%></p>
      </div>
    </div>
  </div>

app/views/sitters/show.html.erb
<section id="sitter-profile">
  <div class="container h-100">
    <div class="row justify-content-center align-self-center pt-3">

      <div class="col mx-auto d-flex flex-column">
        <h1 class="align-self-center">Hi! I am <%= @sitter.user.username%></h1>
            <%= image_tag @sitter.picture, style: "width:75%; border-radius: 50px", src: 'Image not found', onerror: 'this.error=null;this.src="https://pngimage.net/wp-content/uploads/2018/05/default-user-profile-image-png-7.png"', class:"img-responsive align-self-center mb-3" %>
            <h4 class="text-center"><% @sitter.pets.each do |pet| %><span>● <%= pet.animal %>s </span><% end %>
              <h4 class="text-center"><span class="h5 text-muted"> $<%= @sitter.price%> per day</span></h4>
              <h4 class="text-center"><span class="h5 text-italic"><i class="fas fa-phone"></i>
                <%= @sitter.phone %></span></h4>
      </div>

      <div class="col mx-auto d-flex flex-column align-items-center pt-5">
      
        <h4>Available Dates</h4>
        <% if !@sitter.timeslots.empty? %>

          <% @sitter.timeslots.each do |t| %>
          <p><%= t.available_start_date.strftime("%d %b %Y")%> to <%= t.available_end_date.strftime("%d %b %Y")%></p>
          <% end %>

          <% if @sitter.timeslots.length > 0 %>
            <%= link_to 'Book', new_booking_path, :class => 'btn btn-primary' %>
          <% end %>

        <% end %>
      </div>

      <div class="col mx-1 my-1">
        <div class="container-fluid h-100 pt-5">
          <% if @sitter.location %>
            <iframe width="100%" height="100%" frameborder="0" style="border:0" class="img-responsive"
          src="https://www.google.com/maps/embed/v1/search?q=<%= @sitter.location.gsub(/\s+/, '+') %>,+Singapore&key=AIzaSyBLmBOaPbZ6QachL4NResvEtu8ChjOQGfw"
          allowfullscreen></iframe>
          <% else %>
            <%=image_tag "https://joomly.net/frontend/web/images/googlemap/map.png", :class =>'img-responsive', :style=>"width:100%;"%>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row d-flex flex-row justify-content-center align-self-center mt-5">
      <div class="container">
        <h4 class='text-center'>About me</h4>
        <p style="white-space: pre-wrap; overflow-wrap: break-word;" class="text-center"><%= @sitter.description%></p>
      </div>
    </div>
  </div>
</div>