config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'sitters#index'
    get '/index' => 'sitters#index', as: 'main'
    get '/sitters/:id' => 'sitters#show', as: 'sitter'
    get '/profile' => 'sitters#profile', as: 'profile'
    get '/profile/new' => 'sitters#new', as: 'new_profile'
    post '/profile' => 'sitters#create'
    post '/index' => 'sitters#search', as: 'search'

    get '/profile/edit' => 'sitters#edit', as: 'edit_profile'
    patch '/sitters/:id' => 'sitters#update'
    get '/profile/edit/timeslots/:id' => 'timeslots#edit', as: 'edit_timeslot'
    patch '/profile/edit/timeslots/:id' => 'timeslots#update'

    get '/sitters/:id/bookings/new' => 'bookings#new', as: 'new_booking' #testing
    get '/users/bookings' => 'bookings#show', as: 'bookings'
    post '/sitters/:id/bookings' => 'bookings#create', as: 'create_booking'
    patch '/users/bookings' => 'bookings#update', as: 'update_booking'

    get '/timeslots/new' => 'timeslots#new', as: 'new_timeslot'
    post '/timeslots' => 'timeslots#create'
end

app/models/timeslot.rb
require 'date'

class Timeslot < ApplicationRecord

    belongs_to :sitter


    validate :timeslot_logic, on: :create




    def timeslot_logic
        if self.available_start_date.past?
            errors.add(:available_dates, "We can't timetravel yet. Please use a more current date")
        elsif self.available_start_date > self.available_end_date
            errors.add(:available_dates, "End time must be later than Start Time")
        end
    end

end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController

    before_action :authenticate_user!

    def new
        timeslot_check = Timeslot.where(sitter: current_user.sitter)
        if timeslot_check.length > 0
            redirect_to profile_path
        end
    end

    def create
        #check if timeslot has already been exists
        timeslot_check = Timeslot.where(sitter: current_user.sitter)
        if timeslot_check.length > 0
            redirect_to profile_path, flash: { error: "Timeslots already exist" } and return
        end
        @timeslot = Timeslot.new(timeslot_params)

        @timeslot.sitter = current_user.sitter
        if @timeslot.available_start_date == nil || @timeslot.available_end_date == nil
            redirect_to new_timeslot_path, flash: { error: "Timeslot Fields Empty" }
        else
            bookings = Booking.where(status: true).where(sitter: current_user.sitter).where.not('start_date > ? AND end_date > ?', @timeslot.available_end_date, @timeslot.available_end_date).where.not('start_date < ? AND end_date < ?', @timeslot.available_start_date, @timeslot.available_start_date)
            if bookings.length == 0
                if @timeslot.save
                    redirect_to profile_path
                else
                    redirect_to new_timeslot_path, flash: { error: "Something went wrong" }
                end
            else
                redirect_to new_timeslot_path, flash: { error: "Confirmed Booking Exists In Same Timeslot" }
            end
        end
    end

    def edit
        @timeslot = Timeslot.find(params[:id])
    end

    def update
        checks = Timeslot.new(timeslot_params)
        bookings = Booking.where(status: true).where(sitter: current_user.sitter).where.not('start_date > ? AND end_date > ?', checks.available_end_date, checks.available_end_date).where.not('start_date < ? AND end_date < ?', checks.available_start_date, checks.available_start_date)
        if bookings.length == 0
            timeslots = Timeslot.where(sitter: current_user.sitter).where.not(id: params[:id]).where.not('available_start_date > ? AND available_end_date > ?', checks.available_end_date, checks.available_end_date).where.not('available_start_date < ? AND available_end_date < ?', checks.available_start_date, checks.available_start_date)
            if timeslots.length == 0
                if timeslot_params[:available_start_date] <= timeslot_params[:available_end_date]
                    @timeslot = Timeslot.find(params[:id])
                    @timeslot.update(timeslot_params)
                    redirect_to profile_path
                else
                    redirect_to profile_path, flash: { error: "End Must Be Later Than Start Date" }
                end
            else
                redirect_to profile_path, flash: { error: "Timeslot Conflicts with Existing Timeslot"}
            end
        else
            redirect_to profile_path, flash: { error: "Confirmed Booking Exists in Same Timeslot" }
        end
    end

private

    def timeslot_params
        params.require(:timeslot).permit(:available_start_date, :available_end_date)
    end

end

app/views/timeslots/edit.html.erb
<section id="edit-timeslot">
    <div class="container mt-3">
        <h1>Edit Timeslot</h1>

        <%= form_with scope: :timeslot, model: @timeslots, method: "patch", local: true do |form| %>
            <div class="form-row ">
                <div class="form-group col-md-6 ">
                    <%= form.label :available_start_date %><br>
                    <%= form.text_field :available_start_date , :type=>"date", :class=>"form-control", :min=>Date.today, :required => true %>
                </div>
                <div class="form-group col-md-6">
                    <%= form.label :available_end_date %><br>
                    <%= form.text_field :available_end_date , :type=>"date", :class=>"form-control", :min=>Date.today, :required => true %>
                </div>
            </div>
            <div class="actions">
                <%= form.submit class: "btn btn-outline-success" %>
                </div>
        <% end %>
    </div>
</section>

app/views/timeslots/new.html.erb
<div class="container mt-3">
<h1>Add New Timeslot</h1>

<%= form_with scope: :timeslot, url: timeslots_path, local: true do |form| %>
        <div class="form-row ">
            <div class="form-group col-md-6 ">
                <%= form.label :available_start_date %><br>
                <%= form.text_field :available_start_date , :type=>"date", :class=>"form-control", :min=>Date.today %>
            </div>
            <div class="form-group col-md-6">
                <%= form.label :available_end_date %><br>
                <%= form.text_field :available_end_date , :type=>"date", :class=>"form-control", :min=>Date.today %>
            </div>
        </div>
        <div class="actions">
            <%= form.submit class: "btn btn-outline-success" %>
        </div>

<% end %>
</div>